### ISSUE TITLE
A question about equation 2 in the paper

### ISSUE THREAD

**Issue by hallwaypzh** [Animadversio/GAN-Geometry#2]
It seems that both 
![formula](https://render.githubusercontent.com/render/math?math=Hv) and ![formula](https://render.githubusercontent.com/render/math?math=\partial_z(v^Tg(z))) are column vectors, ![formula](https://render.githubusercontent.com/render/math?math=v^T\partial_zg(z)) is a row vector, so i wonder why the second equation holds?
Thanks in advance.

**Comment by Animadversio** [comment]
Sorry for the late response. Tldr, you are right, but computationally it's the same result in Python. 

I think this comes from my **inconsistent convention for tensor shape** when you take the gradient of a tensor towards another tensor. I was appending the index of the gradient to the last dimension of the tensor
In my original thought, shape of `H` is `[n,n]`, `v` is `[n,1]`,  `g(z)` is a column vector `[n,1]`. 
`v^Tg(z)` is a scalar and `\partial_z v^Tg(z)` was shape `[1,n]`. 
`\partial_z g(z)` is of shape `[n,n]` and it's symmetric; In my convention, the index of `g` will be the first index, so I multiply `v` from the left, resulting in shape `[1,n]` which is a row vector. 

But at the computational level as in python, the singleton dimensions are not there; and `v^Tg(z)` is implemented by the jacobian vector product, and the results are the same there. 

One much clearer way to represent this is in an Einstein summation notation, which get rid of the column and rows during derivation. 
`\partial_z (v^T g(z)) = \partial_{z_i}(v_j g_j(z)) =  v_j \partial_{z_i} g_j(z) = (\partial_{z_i} g_j(z)) v_j = (\partial_z g(z)) v` 
<img src="https://render.githubusercontent.com/render/math?math=%5Cpartial_z%20(v%5ET%20g(z))%20%3D%20%5Cpartial_%7Bz_i%7D(v_j%20g_j(z))%20%3D%20%20v_j%20%5Cpartial_%7Bz_i%7D%20g_j(z)%20%3D%20(%5Cpartial_%7Bz_i%7D%20g_j(z))%20v_j%20%3D%20(%5Cpartial_z%20g(z))%20v">
In this view (index of the derivator tensor goes to the left, which is more consistent), `v` should be multiplied from the right, and I will fix that!

**Comment by hallwaypzh** [comment]
Thank u for your detailed reply, it makes much sense now;)
