### ISSUE TITLE
When I use GANForwardHVPOperator, I find some errors reported

### ISSUE THREAD

**Issue by jweihe** [Animadversio/GAN-Geometry#4]
RuntimeError: grad can be implicitly created only for scalar outputs
`        img = self.model.visualize(perturb_vecs)
        resz_img = self.preprocess(img)
        activs = self.objective(resz_img)  # , scaler=True
        # obj = alexnet.features[:10](resz_img)[:, :, 6, 6].sum()  # esz_img.std()
        ftgrad_both = torch.autograd.grad(activs, perturb_vecs, retain_graph=False, create_graph=False, only_inputs=True)[0]`

**Comment by jweihe** [comment]
why this happens?

**Comment by jweihe** [comment]
I found that I was doing a gradient operation on a multidimensional tensor here, so I modified it and so far everything works fine
`        ftgrad_both = torch.autograd.grad(activs.mean(), perturb_vecs, retain_graph=False, create_graph=False, only_inputs=True)[0]`

**Comment by Animadversio** [comment]
Exactly as you read in the error output from torch `RuntimeError: grad can be implicitly created only for scalar outputs` 
so it needs to be a scalar. I think this issue could be closed? 

Happy to hear if you find any other issues. 😸
